#!/usr/bin/env bash
# ============================================================
#  cca-PaaS — Shared nginx + compose generator functions
#  Sourced by docker/setup.sh and docker/setup-cloudflare-ssl.sh
# ============================================================

CF_SSL_DIR_DEFAULT="/etc/cloudflare-ssl"

# Cloudflare Full SSL: Origin Certificate on port 443 + HTTP → HTTPS redirect
generate_nginx_cloudflare_ssl() {
  local domain="$1"
  local cf_ssl_dir="${2:-${CF_SSL_DIR_DEFAULT}}"
  cat > docker/nginx.conf <<NGINXEOF
# Cloudflare trusted proxy ranges
set_real_ip_from 103.21.244.0/22;
set_real_ip_from 103.22.200.0/22;
set_real_ip_from 103.31.4.0/22;
set_real_ip_from 104.16.0.0/13;
set_real_ip_from 104.24.0.0/14;
set_real_ip_from 108.162.192.0/18;
set_real_ip_from 131.0.72.0/22;
set_real_ip_from 141.101.64.0/18;
set_real_ip_from 162.158.0.0/15;
set_real_ip_from 172.64.0.0/13;
set_real_ip_from 173.245.48.0/20;
set_real_ip_from 188.114.96.0/20;
set_real_ip_from 190.93.240.0/20;
set_real_ip_from 197.234.240.0/22;
set_real_ip_from 198.41.128.0/17;
set_real_ip_from 2400:cb00::/32;
set_real_ip_from 2606:4700::/32;
set_real_ip_from 2803:f800::/32;
set_real_ip_from 2405:b500::/32;
set_real_ip_from 2405:8100::/32;
set_real_ip_from 2a06:98c0::/29;
set_real_ip_from 2c0f:f248::/32;
real_ip_header   CF-Connecting-IP;
real_ip_recursive on;

# HTTP -> HTTPS redirect
server {
    listen 80;
    server_name ${domain};
    return 301 https://\$host\$request_uri;
}

# HTTPS server with Cloudflare Origin Certificate
server {
    listen 443 ssl;
    server_name ${domain};

    ssl_certificate     ${cf_ssl_dir}/cert.pem;
    ssl_certificate_key ${cf_ssl_dir}/key.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;
    ssl_session_cache   shared:SSL:10m;
    ssl_session_timeout 10m;

    root /usr/share/nginx/html;
    index index.html;

    location /api/ {
        proxy_pass http://api:8080/api/;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto https;
        proxy_read_timeout 60s;
        proxy_connect_timeout 10s;
    }

    location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg|woff|woff2|ttf|eot)$ {
        expires 1y;
        add_header Cache-Control "public, immutable";
        try_files \$uri =404;
    }

    location / {
        try_files \$uri \$uri/ /index.html;
    }
}
NGINXEOF
}

# Generate docker-compose.override.yml for Cloudflare Full SSL (port 443 + cert volume)
generate_compose_cloudflare_ssl_override() {
  local cf_ssl_dir="${1:-${CF_SSL_DIR_DEFAULT}}"
  cat > docker-compose.override.yml <<OVERRIDEEOF
# Auto-generated by cca-PaaS setup — Cloudflare Full SSL mode
# Adds HTTPS port binding and Cloudflare Origin Certificate volume
services:
  frontend:
    ports:
      - "443:443"
    volumes:
      - ${cf_ssl_dir}:${cf_ssl_dir}:ro
OVERRIDEEOF
}
